//! SeaORM Entity. Generated by sea-orm-codegen 0.2.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "character_public_info")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub character_id: u64,
    #[sea_orm(column_type = "Text")]
    pub character_name: String,
    pub alliance_id: Option<u64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub birthday: Option<String>,
    pub corporation_id: u64,
    pub faction_id: Option<u64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::attackers::Entity")]
    Attackers,
    #[sea_orm(has_one = "super::victims::Entity")]
    Victims,
}

impl Related<super::attackers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Attackers.def()
    }
}

impl Related<super::victims::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Victims.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
