//! SeaORM Entity. Generated by sea-orm-codegen 0.2.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "esi_categories")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub category_id: u64,
    #[sea_orm(column_type = "Text")]
    pub category_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::esi_groups::Entity")]
    EsiGroups,
}

impl Related<super::esi_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EsiGroups.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
