//! SeaORM Entity. Generated by sea-orm-codegen 0.2.3

use datamodels::esi_models::ESIKillmail;
use sea_orm::entity::prelude::*;
use sea_orm::Set;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "killmails")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub killmail_id: u64,
    pub killmail_time: DateTime,
    pub solar_system_id: u64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::attackers::Entity")]
    Attackers,
    #[sea_orm(has_many = "super::killmail_positions::Entity")]
    KillmailPositions,
    #[sea_orm(has_many = "super::victims::Entity")]
    Victims,
}

impl Related<super::attackers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Attackers.def()
    }
}

impl Related<super::killmail_positions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KillmailPositions.def()
    }
}

impl Related<super::victims::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Victims.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl From<ESIKillmail> for ActiveModel {
    fn from(item: ESIKillmail) -> Self {
        crate::entity::killmails::ActiveModel {
            killmail_id: Set(item.killmail_id),
            killmail_time: Set(item.killmail_time),
            solar_system_id: Set(item.solar_system_id),
        }
    }
}
