//! SeaORM Entity. Generated by sea-orm-codegen 0.2.3

pub mod prelude;

pub mod alliances;
pub mod attackers;
pub mod character_public_info;
pub mod corporations;
pub mod esi_categories;
pub mod esi_groups;
pub mod esi_types;
pub mod factions;
pub mod killmail_positions;
pub mod killmails;
pub mod victims;
